apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aws-cost-tracker
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aws-cost-tracker
            port:
              number: 80